site_name: Multi-Level Healthcare Information Modelling Specifications
pages:
    - [index.md, Home]
    - [ExecutiveSummary.md, Executive Summary]
    - [Another.md, Another Page]

theme: readthedocs
